# -*- coding: utf-8 -*-
"""ExercicioObjectDetection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hL2hsMttPtMkBLcmzl0XapvsD0MkrXcb
"""

import cv2
from google.colab import drive
from google.colab.patches import cv2_imshow
drive.mount('/content/drive')

"""Carros"""

imagem = cv2.imread('/content/drive/MyDrive/Curso Visão Computacional/Visão Computacional Guia Completo-20240425T222742Z-001/Visão Computacional Guia Completo/Images/car.jpg')
imagem_cinza = cv2.cvtColor(imagem, cv2.COLOR_BGR2GRAY)
detector_carros = cv2.CascadeClassifier('/content/drive/MyDrive/Curso Visão Computacional/Visão Computacional Guia Completo-20240425T222742Z-001/Visão Computacional Guia Completo/Cascades/cars.xml')
deteccoes = detector_carros.detectMultiScale(imagem_cinza, scaleFactor=1.05, minNeighbors=3, minSize=(32,32), maxSize=(70,70))
for(x,y,w,h) in deteccoes:
  print(w,h)
  cv2.rectangle(imagem, (x,y), (x+w, y+h), (0,255,0), 2)
cv2_imshow(imagem)

"""Relógios"""

imagem = cv2.imread('/content/drive/MyDrive/Curso Visão Computacional/Visão Computacional Guia Completo-20240425T222742Z-001/Visão Computacional Guia Completo/Images/clock.jpg')
imagem_cinza = cv2.cvtColor(imagem, cv2.COLOR_BGR2GRAY)
detector_relogios =  cv2.CascadeClassifier('/content/drive/MyDrive/Curso Visão Computacional/Visão Computacional Guia Completo-20240425T222742Z-001/Visão Computacional Guia Completo/Cascades/clocks.xml')
deteccoes = detector_relogios.detectMultiScale(imagem_cinza, scaleFactor=1.03, minNeighbors=1)
for(x,y,w,h) in deteccoes:
  print(w,h)
  cv2.rectangle(imagem, (x,y), (x+w, y+h), (0,0,255), 2)
cv2_imshow(imagem)

"""Corpos Inteiros"""

imagem = cv2.imread('/content/drive/MyDrive/Curso Visão Computacional/Visão Computacional Guia Completo-20240425T222742Z-001/Visão Computacional Guia Completo/Images/people3.jpg')
imagem_cinza = cv2.cvtColor(imagem, cv2.COLOR_BGR2GRAY)
deteccao_corpo = cv2.CascadeClassifier('/content/drive/MyDrive/Curso Visão Computacional/Visão Computacional Guia Completo-20240425T222742Z-001/Visão Computacional Guia Completo/Cascades/fullbody.xml')
deteccoes = deteccao_corpo.detectMultiScale(imagem_cinza, scaleFactor=1.05, minNeighbors=11, minSize=(50,50), maxSize=(100,200))
for(x,y,w,h) in deteccoes:
  print(w,h)
  cv2.rectangle(imagem, (x,y), (x+w, y+h), (255,0,0), 2)
cv2_imshow(imagem)